#!/usr/bin/env python3
"""
Modern Robotics Capstone Project - Usage Examples

This script demonstrates how to use the mobile manipulation software.
Run this from the project root directory.
"""

def main():
    print("Modern Robotics Capstone Project - Usage Examples")
    print("=" * 50)
    print()
    print("Generate complete submission package:")
    print("  python main.py")
    print("  python main.py submission")
    print()
    print("Run individual scenarios:")
    print("  python main.py best")
    print("  python main.py overshoot") 
    print("  python main.py newTask")
    print()
    print("Run all control modes:")
    print("  python main.py feedforward")
    print("  python main.py proportional")
    print("  python main.py feedforward_pi")
    print("  python main.py all")
    print()
    print("Run tests:")
    print("  pytest tests/")
    print("  pytest tests/test_milestone4.py")
    print("  pytest tests/test_milestone3.py")
    print("  pytest tests/test_milestone2.py")
    print()
    print("Module usage examples:")
    print("  # Import trajectory generator")
    print("  from code.trajectory_generator import TrajectoryGenerator")
    print("  ")
    print("  # Import next state simulator")
    print("  from code.next_state import NextState")
    print("  ")
    print("  # Import feedback control")
    print("  from code.feedback_control import FeedbackControl")
    print("  ")
    print("  # Import complete capstone runner")
    print("  from code.run_capstone import run_capstone")
    print("  ")
    print("  # Import scenario functions")
    print("  from code.scenarios import (")
    print("      scenario_best, scenario_overshoot, scenario_new_task")
    print("  )")
    print()
    print("Project structure:")
    print("  code/main.py               - Unified command-line interface")
    print("  code/                      - Core implementation modules")
    print("  tests/                     - Comprehensive test suite")
    print("  output/                    - Generated trajectory files")
    print("  requirements.txt           - Python dependencies")

if __name__ == "__main__":
    main()
